name: Build Push to Dockerhub

on:
  push:
    branches: [main]

jobs:
  build-push: #job 1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      
      - name: Build and Push to Dockerhub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{DOCKERHUB_USER}}/python-linting-app:latest
            ${{DOCKERHUB_USER}}/python-linting-app:${{github.sha}}
            ${{DOCKERHUB_USER}}/python-linting-app:${{github.ref_name}}