name: practice python linting app

on:
  push:
    branches: [main]

jobs: 

  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Code
        uses: actions/checkout@v5

      - name: python setup
        uses: actions/setup-python@v7
        with:
          python-version: 3.13
      
      - name: Installing dependencies
        run: pip install -r requirements.txt

      - name: Linting code
        run: flake8 app.py

      - name: Start Application
        run: |
          python app.py > app.log 2>&1 &
          sleep 30
          cat app.log

      - name: Test application
        run: curl http://localhost:5000