name: Deploy Flask App

# Allows the deployment workflow to be started manually
on:
    workflow_run:
        workflows: ["Docker Build and Push"] # Must match the exact name of the first workflow
        types:
            - completed
        branches:
            - main

jobs:
    deploy:
        # Docker Hub user and unique image tag for this deployment
        env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
            DOCKER_TAG: ${{ github.sha }}

        # Run deployment on our EC2 self-hosted runner
        runs-on: self-hosted

        steps:

            # Download the latest repository code
            - name: Checkout code
              uses: actions/checkout@v5

            # Stop the old container and recreate it with the latest image
            - name: Deploy with Docker Compose
              run: docker compose down && docker compose up -d --build --force-recreate