name: Complete DevSecOps Pipeline

on:
    push:
        branches: [main]

jobs:
#====================CI Part====================
    code-quality:
        uses: ./.github/workflows/code-quality.yml
    
    secret-scan:
        uses: ./.github/workflows/secrets-scan.yml
        secrets: inherit

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

    docker-scan:
        uses: ./.github/workflows/docker-lint.yml

#====================CD Part====================
    build:
        needs: [code-quality, secret-scan, dependency-scan, docker-scan]
        uses: ./.github/workflows/docker-build-push-workflow.yml
        secrets: inherit

    trivy:
        needs: [build]
        uses: ./.github/workflows/image-scan.yml
        secrets: inherit

#====================Deploy to Production====================

    deploy:
        needs: [trivy]
        uses: ./.github/workflows/deploy-to-prd-server.yml
        secrets: inherit