name: Portfolio Workflow

on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    portfolio:
        runs-on: ubuntu-latest

        environment:
            name: github page
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Setup github page
              uses: actions/configure-pages@v5

            - name: Upload static files
              uses: actions/upload-pages-artifact@v3
              with:
                name: index.html        # Name of the downloadable ZIP archive
                path: ./index.html 

            - name: Deploy pages
              uses: actions/deploy-pages@v4

