#API Keys, sensitive data, credentials
#Gitleaks
name: Secrets Scan

on:
    workflow_call:

jobs:
    secret-scan:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v6
              with:
                fetch-depth: 0
            
            - name : Clean Gitleaks temp file
              run: sudo rm -rf /tmp/gitleaks.tmp /tmp/gitleaks-*
            
            - name: Run GitLeaks Scanner
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} #github generate it automatically